---
name: kong

director_uuid: 63ddb6a6-d6fe-40e1-b16b-2ff6b2034c79

instance_groups:
- name: kong
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
    static_ips:
    - 10.244.20.2
  jobs:
  - name: docker
    release: docker
  - name: postgres
    release: postgres
    properties:
      databases:
        databases:
        - name: kong
          citext: true
        port: 5432
        roles:
        - name: kong
          password: kong
          permissions:
          - "SUPERUSER"
  - name: kong
    release: kong
- name: kongConfig
  instances: 1
  azs: [z1]
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: kongConfig
    release: kong
    properties:
      name: "myApi"
      hosts: "fakehost.com"
      upstream_url: "http://www.example.com"

variables: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: kong
  version: latest
- name: postgres
  version: 23
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=23
  sha1: 4b5265bfd5f92cf14335a75658658a0db0bca927
- name: docker
  version: 30.1.5
  url: https://bosh.io/d/github.com/cf-platform-eng/docker-boshrelease?v=30.1.5
  sha1: bc592e3f75c3dfd4c91efe91a3bb8a3ca716ad52