---
processes:
- name: docker
  executable: /var/vcap/packages/docker/bin/docker
  args: []
  ephemeral_disk: true
  persistent_disk: false
  env:
    PORT: <%= p("port") %>
  limits:
    memory: 1G
    open_files: 1024

# example at https://github.com/cloudfoundry-incubator/bpm-release/blob/master/jobs/bpm-test-agent/templates/bpm.yml.erb
# example at https://github.com/cloudfoundry-incubator/bpm-release/blob/master/jobs/bpm-test-agent/templates/bpm.yml.erb
